version: '3.7'
services:
  rails:
    build: &rails_build
      context: .
    volumes: &rails_volumes
      - $PWD:/app
      - $PWD/node_modules:/app/node_modules
      - $PWD/vendor/cache:/app/vendor/cache
    env_file: &env
      - .env
    depends_on:
      - postgres
      - redis
    ports:
     - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/jungledemo
      - TEST_DATABASE_URL=postgresql://postgres:password@postgres/jungledemotest
  webpacker:
    build: *rails_build
    volumes: *rails_volumes
    env_file: *env
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - LANG=C.UTF-8
      - RAILS_LOG_TO_STDOUT=true
  postgres:
      image: "postgres:10.3-alpine"
      ports: ["5432:5432"]
      volumes:
        - $HOME/docker_data/jungledemo:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=jungledemo
        - POSTGRES_PASSWORD=password
  redis:
    image: "redis:5.0.5-alpine"
